### ISSUE TITLE
How to use the annotator with only mesh and RGB images?

### ISSUE THREAD

**Issue by ewrfcas** [EPFL-VILAB/omnidata#16]
Thanks for your good works! 
The paper said that the annotator can be extended to Tanks and Temples. I would like to know how to use the annotator to render depths for Tanks and Temples with only mesh(no texture) and RGB images(no camera poses)? And what does 'aligned' in 'aligned RGB images' mean in this paper?

**Comment by alexsax** [comment]
Hi @ewrfcas 

'Aligned' in this case means that we do have camera pose for the RGB images. For T+T the camera poses are [available](https://www.tanksandtemples.org/download/). 

Using the mesh for geometry and RGB + camera poses for images is how we generated the Taskonomy and 2D3DS datasets. You can look at the [demo](https://github.com/EPFL-VILAB/omnidata/tree/main/omnidata_annotator) for an example, though the demo uses textured meshes. The only difference is that you want to use the script [create_rgb_images.py](https://github.com/EPFL-VILAB/omnidata/blob/main/omnidata_annotator/scripts/create_rgb_images.py) instead of [create_rgb_images_textured.py](https://github.com/EPFL-VILAB/omnidata/blob/main/omnidata_annotator/scripts/create_rgb_images_textured.py). As for how to do this, see the entrypoint [run_demo.sh](https://github.com/EPFL-VILAB/omnidata/blob/main/omnidata_annotator/run-demo.sh)
