### ISSUE TITLE
Surface normal model

### ISSUE THREAD

**Issue by hit421** [EPFL-VILAB/omnidata#23]
Hello! I wonder that is the "Surface Normal Estimation" model same as the "Surface Normals Extracted from Predicted Depth"  model? 
If they are not the same, could you provide the model for "Surface Normals Extracted from Predicted Depth"? 
If they're the same, I input as follows:
![图片](https://user-images.githubusercontent.com/45631341/198813013-58daf213-2cdd-45b9-ab0b-7d2a014aa3db.png)
![图片](https://user-images.githubusercontent.com/45631341/198813015-2d44eb10-e975-40c3-9375-dff954c154d3.png)
The results in red are inconsistent.
I would appreciate it if you could help me.

**Comment by alexsax** [comment]
Hi, these are two totally different models.
The "omnidata normal" network is trained to estimate normals from RGB. In the second output the network fails because the input image is not an RGB image but a scaled + shifted depth image that's been remapped to RGB space.

The "depth -> normal" network is just a little wrapper function we wrote to analytically estimate normals from the output of the depth network. It doesn't require any training, it's a classical approach :). It works reasonably well because (1) it's a fact about depth and (2) midas is trained with a gradient-matching loss that does something similar.

**Comment by TeCai** [comment]
Hi, thanks for the answering. Is the wrapper function you mentioned in the answer included in the code provided? I am having troubles finding them.

**Comment by ZachL1** [comment]
@alexsax 
I have the same problem as @TeCai , can you provide the wrapper function "depht -> normal"?
Thanks a lot!
