### ISSUE TITLE
Taskonomy tiny subset number of buildings mismatch

### ISSUE THREAD

**Issue by thipokKub** [EPFL-VILAB/omnidata#3]
I am trying to download subset of Taskonomy dataset using the following command
```
$> omnitools.download rgb segment_semantic depth_zbuffer normal keypoints2d edge_texture --components taskonomy --subset tiny --dest ./omnidata_starter_dataset/ --connections_total 40 --agree --only_download True
```
The total number of files downloaded is `204` files (`204 = 34*6`), but according tot the tiny subset [spec](https://github.com/StanfordVL/taskonomy/blob/master/data/README.md#dataset-splits) it should have downloaded `210` files (`210 = 35*6`), which suggest one of the building is missing

So I tested with the downloaded filename and found that `woodbine` building is missing. Is this an expected behaviour?

Also `edge_texture__taskonomy__wiconisco.tar` have surprisingly a lot of corrupted png

**Comment by alexsax** [comment]
Hi, thanks for flagging this. Some of the models are indeed missing because the files were corrupted and now are lost forever 🤷. Those files are here: https://github.com/EPFL-VILAB/omnidata-tools/blob/main/omnidata_tools/dataset/starter_dataset/component_datasets/taskonomy/__init__.py#L15

Good point about wisconisco and you can see there's a line commented out flagging the texture edges. I guess we decided to keep that model since few people use the texture edges (and they're simple to just regenerate on-the-fly using a standard edge detector). We should just remove it from our servers, I think.
