### ISSUE TITLE
how to convert omnidata normal to pytorch3d coordinate

### ISSUE THREAD

**Issue by lcc815** [EPFL-VILAB/omnidata#58]
hi, 

is there any way to convert omnidata normal to pytorch3d coordinate?

I noticed #13 discussed this question, but what is the input `x` of `_thunk` function, and why should we do in that way?

thanks a lot!

**Comment by alexsax** [comment]
If you use the [dataloader](https://github.com/EPFL-VILAB/omnidata/tree/main/omnidata_tools/torch/dataloader) in this repo, it will use [this function](https://github.com/EPFL-VILAB/omnidata/blob/ab14b650e65193f1fc291f8517281366bdffbe23/omnidata_tools/torch/dataloader/transforms.py#L125) to output the normals in P3D coordinate space.

In the email you sent you asked 
> for omnidata, the straight up vector normal will be ~(0.5, 0., 0.5), which is a little strange.
Images are stored as 3-channel uint8, I assume and most libraries load them as integers or into the range [0,1]. Which is why the function shifts and rescale them into the range [-1, 1] .

This is the colormap of the images on disk. The image is of a unit sphere
![image](https://github.com/EPFL-VILAB/omnidata/assets/5157485/20c44ba4-140f-4445-a48a-2887596b4e53)

Hope this helps :)

**Comment by lcc815** [comment]
This helps!
Thanks for your reply!
